### ISSUE TITLE
Please add interp_method=none attribute to vector diagnostics

### ISSUE THREAD

**Issue by ceblanton** [NOAA-GFDL/SIS2#65]
Vector diagnostic fields should have attribute interp_method=none set so fregrid won't attempt to regrid them (as fregrid isn't able to regrid tripolar vector fields to lat/lon).

Please set these 10 diagnostics to have attribute interp_method=none set:

FA_X, FA_Y, FI_X, FI_Y, 
IX_TRANS, IY_TRANS,
UI, VI, UO, VO

Thank you,
Chris Blanton

**Comment by Hallberg-NOAA** [comment]
This issue was addressed in commit 916cb4a5ce812df5231cb680e76df4e6e7345325, and has been closed.
  In the future, requests for SIS2 code changes to accommodate the limitations of FRE would be better addressed by trying out new code on fully a tested branch (including whatever FRE capabilities are supposed to be exercised), followed by a pull request. The standard testing for SIS2 does not use FRE, and hence can not be relied upon to evaluate interactions between FRE and the output from SIS2.
