### ISSUE TITLE
Incorrect diagnostic being posted

### ISSUE THREAD

**Issue by nicjhan** [NOAA-GFDL/SIS2#70]
It looks like there's a typo around line 242 of SIS_slow_thermo.F90 . The same data is being posted to two different diagnostics. 

This is causing the diagnostic tests on Jenkins to fail:

https://accessdev.nci.org.au/jenkins/job/mom-ocean.org/job/MOM6_diagnostics/345/console

**Comment by adcroft** [comment]
[L242 of SIS_slow_thermo.F90](https://github.com/NOAA-GFDL/SIS2/blob/87ddb5846f750149bfaf6e2bc0fd8e39551d0c69/SIS_slow_thermo.F90#L242) is posting a 2D array:
```fortran
allocate(FIA%Tskin_avg(isd:ied, jsd:jed)) ; FIA%Tskin_avg(:,:) = 0.0 ! diag
```
but the trace back is via [L491 of SIS_diag_mediator.F90](https://github.com/NOAA-GFDL/SIS2/blob/87ddb5846f750149bfaf6e2bc0fd8e39551d0c69/SIS_diag_mediator.F90#L491) which is in s/r post_data_3d().

I must be looking at the wrong version. What version of SIS2 is this issue for?

PS> The same field is being posted twice but based on the registration I think it is intentional - one looks like the standard name of the other.

**Comment by nicjhan** [comment]
unfortunately the traceback line numbers are off! The problem is the line above:

post_data(FIA%id_sw_dn, FIA%flux_sw_dn, CS%diag)

flux_sw_dn is now a 3d array but registered on 2d axes.
