### ISSUE TITLE
CMIP requests sea-ice surface temperature in K (not C)

### ISSUE THREAD

**Issue by ceblanton** [NOAA-GFDL/SIS2#92]
Units for sea-ice surface temperature (sitemptop) are currently degrees Celsius while the CMIP6 Data Request specifies Kelvins.

http://clipc-services.ceda.ac.uk/dreq/u/5914a456-9e49-11e5-803c-0d0b866b59f3.html

While this can be converted in post-processing, updating it in the model would provide a more permanent fix.

**Comment by Hallberg-NOAA** [comment]
Sea surface temperatures make much more sense if reported in degC.  However, we will add new CMOR specific variable for the sea-ice surface temperature in degK.

**Comment by Hallberg-NOAA** [comment]
SIS2 PR #146 added the new variable sitemptop_CMOR that uses the recommended CMOR units of Kelvin instead of the much more common and sensible practice of using degC.  If anyone is using output for anything but CMOR stuff, I strongly urge the continued use of sitemptop, which SIS2 will continue to report in degC.
