### ISSUE TITLE
Sea-ice volume should be averaged over grid cell area (not ice area)

### ISSUE THREAD

**Issue by ceblanton** [NOAA-GFDL/SIS2#93]
@MichaelWinton found that Sea-ice volume (sivol) is currently averaged over ice area, while CMIP6 requests sea-ice volume over grid-cell area.

http://clipc-services.ceda.ac.uk/dreq/u/71291d86-faa7-11e6-bfb7-ac72891c3257.html

**Comment by nikizadehgfdl** [comment]
@adcroft , @Hallberg-NOAA  At the request of CMIP6  , @MichaelWinton coded the following mods to address this issue. @underwoo recommends that two separate maintenance branches be made in SIS2, one for ESM4 and one for CM4 with the changes indicated by the following branches from my fork. These are the same changes to a single line of code in SIS_dyn_trans.F90, but since CM4 and ESM4 start from different versions of the code and are requesting only these changes and nothing else (for now) there has to be two different maintenance branches:

CM4 mod to commit d57d276233989 :  nikizadehgfdl:nikizadehgfdl/mikewinton_cmip6units_4CM4

ESM4 mod to commit b47317d68336 :  nikizadehgfdl:nikizadehgfdl/mikewinton_cmip6units

Also, please make two tags on the mom6-examples maintenance branches that would checkout these two mods on SIS2.

**Comment by Hallberg-NOAA** [comment]
SIS2 PR #146 added the new variable sivol_CMOR that does the averaging over the entire cell.

  As a side note, the correction that @nikizadehgfdl proposed to address this issue with PR #94 would have worked had the nominal density of ice been set before it was used.
